# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Ecrin/Desktop/Yeni klasör/hasta_ekle.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import Patient
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QVBoxLayout, QFormLayout, QLabel, QLineEdit, QComboBox, QDateEdit, QPushButton, QStatusBar, QWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(425, 326)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 421, 331))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 411, 211))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        
        self.lbl_name = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_name.setObjectName("lbl_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_name)
        self.txt_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_name.setObjectName("txt_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_name)
        
        self.lbl_birth = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_birth.setObjectName("lbl_birth")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_birth)
        self.date_ = QtWidgets.QDateEdit(self.formLayoutWidget)
        self.date_.setObjectName("date_")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.date_)
        
        self.lbl_ide = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_ide.setObjectName("lbl_ide")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_ide)
        self.txt_identity = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_identity.setObjectName("txt_identity")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.txt_identity)
        
        self.lbl_spe = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_spe.setObjectName("lbl_spe")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_spe)
        self.box_spe = QtWidgets.QComboBox(self.formLayoutWidget)
        self.box_spe.setObjectName("box_spe")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.box_spe)
        
        self.lbl_doc = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_doc.setObjectName("lbl_doc")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_doc)
        self.box_dctr_name = QtWidgets.QComboBox(self.formLayoutWidget)
        self.box_dctr_name.setObjectName("box_dctr_name")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.box_dctr_name)
        
        self.lbl_tri = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_tri.setObjectName("lbl_tri")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_tri)
        self.box_triage_clr = QtWidgets.QComboBox(self.formLayoutWidget)
        self.box_triage_clr.setObjectName("box_triage_clr")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.box_triage_clr)
        
        self.btn_save = QtWidgets.QPushButton(self.groupBox)
        self.btn_save.setGeometry(QtCore.QRect(150, 240, 111, 51))
        self.btn_save.setObjectName("btn_save")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        # Hasta instance
        self.hasta = Hasta.Patient()
        
        self.box_spe.addItems(self.doctor.specialization)
        self.box_dctr_name.addItems(self.doctor_name)
        self.box_triage_clr.addItems(self.triage_color)
        
        # Connect the save button to the add_patient function
        self.btn_save.clicked.connect(self.add_patient)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.lbl_name.setText(_translate("MainWindow", "Name:"))
        self.lbl_birth.setText(_translate("MainWindow", "Birthdate:"))
        self.lbl_ide.setText(_translate("MainWindow", "Identity:"))
        self.lbl_spe.setText(_translate("MainWindow", "Specialization:"))
        self.lbl_doc.setText(_translate("MainWindow", "Doctor Name:"))
        self.lbl_tri.setText(_translate("MainWindow", "Triage Color:"))
        self.btn_save.setText(_translate("MainWindow", "Save"))

    def add_patient(self):
        name = self.txt_name.text()
        birthdate = self.date_.date().toString(QtCore.Qt.ISODate)
        identity = self.txt_identity.text()
        specialization = self.box_spe.currentText()
        doctor_name = self.box_dctr_name.currentText()
        triage_color = self.box_triage_clr.currentText()
        
        self.hasta.add_patient(name, birthdate, identity, specialization, doctor_name, triage_color)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())