# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Ecrin/Desktop/Yeni klasör/doctor_update.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import Doctor

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(442, 322)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 421, 331))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 411, 211))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txt_new_dctr_name = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_new_dctr_name.setObjectName("txt_new_dctr_name")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_new_dctr_name)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.txt_new_dctr_surname = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_new_dctr_surname.setObjectName("txt_new_dctr_surname")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_new_dctr_surname)
        self.box_new_dctr_spe = QtWidgets.QComboBox(self.formLayoutWidget)
        self.box_new_dctr_spe.setObjectName("box_new_dctr_spe")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.box_new_dctr_spe)
        self.box_new_aca_rank = QtWidgets.QComboBox(self.formLayoutWidget)
        self.box_new_aca_rank.setObjectName("box_new_aca_rank")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.box_new_aca_rank)
        self.txt_new_pass = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_new_pass.setObjectName("txt_new_pass")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.txt_new_pass)
        self.btn_dctr_update = QtWidgets.QPushButton(self.groupBox)
        self.btn_dctr_update.setGeometry(QtCore.QRect(150, 240, 111, 51))
        self.btn_dctr_update.setObjectName("btn_dctr_update")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        self.doctor = Doctor.Doktor()
        
        # Add items to combo boxes
        self.box_new_aca_rank.addItems(Doctor.academic_rank)
        self.box_new_dctr_spe.addItems(Doctor.specialization)

        # Connect the button to the update_doctor method
        self.btn_dctr_update.clicked.connect(self.update_doctor)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.label.setText(_translate("MainWindow", "New Name:"))
        self.label_2.setText(_translate("MainWindow", "New Surname:"))
        self.label_3.setText(_translate("MainWindow", "New Academic Rank:"))
        self.label_5.setText(_translate("MainWindow", "New Specialization:"))
        self.label_4.setText(_translate("MainWindow", "New Password:"))
        self.btn_dctr_update.setText(_translate("MainWindow", "Update"))
    
    def update_doctor(self):
        new_doktor_name = self.txt_new_dctr_name.text()
        new_doctor_surname = self.txt_new_dctr_surname.text()
        new_academic_rank = self.box_new_aca_rank.currentText()
        new_specialization = self.box_new_dctr_spe.currentText()
        new_password = self.txt_new_pass.text()
        
        self.doctor.update_doctor(new_doktor_name, new_doctor_surname, new_academic_rank, new_specialization, new_password)

        # Optionally, you can add a message box to confirm the update
        QtWidgets.QMessageBox.information(None, "Success", "Doctor updated successfully.")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
