# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Ecrin/Desktop/Yeni klasör/bas_hemsire.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(211, 337)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 191, 301))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_dktr_ekle = QtWidgets.QPushButton(self.groupBox)
        self.btn_dktr_ekle.setObjectName("btn_dktr_ekle")
        self.verticalLayout.addWidget(self.btn_dktr_ekle)
        self.btn_dktr_gncl = QtWidgets.QPushButton(self.groupBox)
        self.btn_dktr_gncl.setObjectName("btn_dktr_gncl")
        self.verticalLayout.addWidget(self.btn_dktr_gncl)
        self.btn_dktr_sl = QtWidgets.QPushButton(self.groupBox)
        self.btn_dktr_sl.setObjectName("btn_dktr_sl")
        self.verticalLayout.addWidget(self.btn_dktr_sl)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Doctors"))
        self.btn_dktr_ekle.setText(_translate("MainWindow", "Add Doctor"))
        self.btn_dktr_gncl.setText(_translate("MainWindow", "Update Doctor"))
        self.btn_dktr_sl.setText(_translate("MainWindow", "Delete Doctor"))
        self.pushButton.setText(_translate("MainWindow", "Update Password"))

    def open_add_doctor(self):
        